# 生产环境配置
# 调试模式
debug: false

# 允许跨域的域名
domainName: "*"

# 监听端口
port: 8080

# jwt密钥
jwtSigningKey: "****************"

# 静态资源路径
custom:
  staticSourcePath: /www/blog/images
  staticUrl: /blog-static/staticSource/
  url: https://deslre.xyz/blog-static/staticSource/

carousel:
  sexApi: https://deslre.xyz/blog-static/staticSource/bg/sex/
  sceneryApi: https://deslre.xyz/blog-static/staticSource/bg/scenery/

# postgresql数据库
postgresql:
  host: "localhost"
  user: "postgres"
  password: 200381
  dbName: "deslreyblog"
  port: 5432

# redis数据库
redis:
  host: "localhost"
  user: ""
  password: "200381"
  dbName: 1
  port: 6379
  size: 10
